buildscript {
    ext.kotlin_version = '1.8.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.1' // Add this line
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects { subproject ->
    if (subproject.name == "audioplayers_android") {
        subproject.plugins.withId("com.android.library") {
            subproject.android {
                namespace = "xyz.audioplayers.android"
            }
        }
    }
}


rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

subprojects { subproject ->
    if (subproject.name == "blurhash") {
        subproject.plugins.withId("com.android.library") {
            subproject.android {
                namespace = "dev.blurhash.library"
            }
        }
    }
}
